### ISSUE TITLE
Please consider tagging a commit

### ISSUE THREAD

**Issue by RaitoBezarius** [CESNET/netconf-cli#21]
Hi there, thank you for the amazing piece of software, I would like to package a CLI for netconf and I was aware of netopeer2 and it seems like this is recommended alternatively, unfortunately there's no tag which makes it hard to package for upstream distributions.

Would you consider doing a release?

**Comment by jktjkt** [comment]
I understand that it's convenient for downstream projects to "rely on something". That said, we're big fans of rolling releases, and we're deploying from `master` branch all the time, and we have CI in place so that `master` only changes when all tests pass. All that means that when we start tagging these releases, they will really only be just some arbitrary snapshots that are tagged at random points in time, with no additional QA. The only difference will be a new object below `.git/refs/tags/`, so instead of knowing that you're on commit 7d4c9f13, you'll know that you're on release `123`.

Again, I understand that it's convenient, but I'd love to get the expectations straight, and to clearly state that there will be no actual benefits in "stability", etc.

**Comment by jktjkt** [comment]
Just FYI, we've tagged a new release (and as I said above, it's really an arbitrary point in the development history). We'll likely be doing that every now and then, mostly at random.
